### ISSUE TITLE
error on loading and working with kilosort dataset

### ISSUE THREAD

**Issue by pozel** [djoshea/neuropixel-utils#14]
Hi,

I am wondering if neuropixel utils is compatible with kilosort 2.5 and kilosort 3? I am able to load my kilosort 2.5 sorted data into the KilosortDataset object. However, I don't have a RawDataset and many other fields in my structure. Here's a picture for reference. Any thoughts on this?

Thanks so much!
<img width="132" alt="Screen Shot 2021-08-05 at 3 26 26 PM" src="https://user-images.githubusercontent.com/67648249/128409278-0c0e5438-b624-486e-8894-c242d98bf7e5.png">

**Comment by djoshea** [comment]
Hi @pozel, I'm actually not sure. I haven't had a chance to try it myself yet. I think when you created the KilosortDataset object, the code wasn't able to find a SpikeGLX `.ap.bin` dataset (called ImecDataset in the repo) in the same folder. If it is in a separate folder, you can create the ImecDataset object yourself [ see https://djoshea.github.io/neuropixel-utils/imec_dataset/#constructing-a-neuropixelimecdataset ], and then pass it to the KilosortDataset constructor:

```matlab
ks = Neuropixel.KilosortDataset("/path/to/kilosort_outputs", 'imecDataset', imec) % imec is your ImecDataset object
```

The missing `raw_dataset` means you can't go back and extract the raw waveforms or other snippets of data from the raw data files but in general everything else should be fine. `meta` is also missing since it is loaded from the `.ap.meta` file accompanying your SpikeGLX data. And `concatenationInfo` is only relevant if you've spliced a few SpikeGLX files together into a continuous recording [ as in https://djoshea.github.io/neuropixel-utils/imec_dataset/#concatenating-multiple-files-together ], so that's fine.

The real question is whether any of the analysis tools work correctly. Try going through the analyses on this page [ https://djoshea.github.io/neuropixel-utils/analysis/ ] and see if they work?

**Comment by pozel** [comment]
Analysis tools are working--thanks so much for your help!
