### ISSUE TITLE
Output metadata is incorrect

### ISSUE THREAD

**Issue by billkarsh** [djoshea/neuropixel-utils#18]
Output files misspell at least these tags {~imroTbl, ~snsChanMap, ~snsShankMap}. This causes subsequent pipeline tools to crash.

**Comment by djoshea** [comment]
Hi Bill, thanks! It's been a while since I've looked at this code, and at the time (2018) I was guessing at the metadata, and before I knew about your CatGT and TPrime. 

Can you unpack what you mean by misspell here? What were you doing to generate a new metadata file? Were you running a processing pipeline like this https://djoshea.github.io/neuropixel-utils/imec_dataset/#modifying-a-dataset-during-copy-to-new-location

I think in the call to writeModifiedAPMeta, these are the three fields that I prefix the fields with a tilde because that's how they appear in my .{band}.meta files, and stripping the tilde led to errors with other tools.
https://github.com/djoshea/neuropixel-utils/blob/6a80b45a2057e51e75cb89e05401e50867a7ce3f/%2BNeuropixel/ImecDataset.m#L1907

What are the fields supposed to be? What is the correct output? Thanks!

**Comment by billkarsh** [comment]
The tilde is required. I am reacting to a bug report about a CatGT crash that I got from a user. The cause was metadata created by neuropixel-utils where the tilde character was absent. I've now looked at your code and it does appear to explicitly add a tilde for those items, though I have never run/tested your code myself. I am guessing that the user's version predates this. If the tilde is present in current code you can close the issue. Thanks for checking this out.

**Comment by djoshea** [comment]
Ah, okay. Looks like I fixed this in 2021 https://github.com/djoshea/neuropixel-utils/commit/ae56e18d862acf46f1f57915ffa87ae1e8769cfa

Please send the user my way if it's not fixed by a pull and I can help track down the issue.

Wish I'd known of the full complement of tools you'd written when I started writing my toolkit! Thanks!

**Comment by zhangxiaoxing** [comment]
I am that user, and I'm just about to dig into things when you guys already resolved it.  That's impressive. Thanks everyone!

Just in case someone else searched for this, adding 3 tildes (~) before the imroTbl, snsChanMap, snsShankMap entry in the modified metafile is sufficient to restore CatGT functionality.
