### ISSUE TITLE
error while trying to exclude specific time window 

### ISSUE THREAD

**Issue by MizrahiTeam** [djoshea/neuropixel-utils#6]
Hello,
I have been trying to excise time windows from the raw data using the timeShifts function with the following commands:

idxStartList=100;
idxStopList=round( imec.nSamplesAP/100 ) ;
timeShifts = Neuropixel.TimeShiftSpec.buildToExciseGaps(idxStartList, idxStopList);

[imecOut] = imec.saveTranformedDataset(cleanedPath, 'transformAP', { @timeShifts },'writeAP', true, 'writeLF', false);

and got the following error:

Error in
Neuropixel.ImecDataset/writeConcatenatedFileMatchGains/writeCatFile
(line 1605)
                                data = fn(imecList{iF}, data,
                                chIds, source_idx);

Error in Neuropixel.ImecDataset.writeConcatenatedFileMatchGains
(line 1457)
                writeCatFile(outFile, chIndsByFile, 'ap',
                multipliers, chunkSize, p.Results.transformAP,
                timeShiftsAP, dryRun);

Error in Neuropixel.ImecDataset/saveTranformedDataset (line 991)
            imecOut =
            Neuropixel.ImecDataset.writeConcatenatedFileMatchGains({df},
            outPath, p.Results);

I'd appreciate your help with understanding what I've been doing wrong.
Many thanks,
Ido Maor

**Comment by djoshea** [comment]
Hey Ido,

Sorry for the delay. The issue is that timeShifts should be passed as a separate parameter `timeShiftsAP` (since you're basing the indices off the AP band, otherwise you would use `timeShiftsLF`). 

So you would want something like:
```matlab
imecOut = imec.saveTranformedDataset(cleanedPath, 'timeShiftsAP', timeShifts, ...
    'writeAP', true, 'writeLF', false);
```

You can also pass `transformAP` if you want additional processing to be performed. This definitely wasn't clear in the docs, so I just updated the description at https://djoshea.github.io/neuropixel-utils/imec_dataset/#excising-time-windows

Hope this helps!
Dan
